"""Update second interview fields

Revision ID: cfa8b8c00463
Revises: 331ae9570586
Create Date: 2025-02-17 17:34:55.198390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfa8b8c00463'
down_revision: Union[str, None] = '331ae9570586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('second_interviews', sa.Column('pass_fail', sa.String(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('sincerity', sa.String(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('team_love', sa.String(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('charm', sa.String(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('humility', sa.String(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('second_interviews', 'problem_solving')
    op.drop_column('second_interviews', 'career_vision')
    op.drop_column('second_interviews', 'logical_thinking')
    op.drop_column('second_interviews', 'technical_skills')
    op.drop_column('second_interviews', 'leadership')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('second_interviews', sa.Column('leadership', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('technical_skills', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('logical_thinking', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('career_vision', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('second_interviews', sa.Column('problem_solving', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('second_interviews', 'notes')
    op.drop_column('second_interviews', 'humility')
    op.drop_column('second_interviews', 'charm')
    op.drop_column('second_interviews', 'team_love')
    op.drop_column('second_interviews', 'sincerity')
    op.drop_column('second_interviews', 'pass_fail')
    # ### end Alembic commands ###
