"""Update final interview fields

Revision ID: ef3946e7dbfa
Revises: cfa8b8c00463
Create Date: 2025-02-17 17:50:37.291586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef3946e7dbfa'
down_revision: Union[str, None] = 'cfa8b8c00463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('final_interviews', sa.Column('pass_fail', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('assertion', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('excuse', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('sincerity', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('avoidance', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('initiative', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('team_love', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('charm', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('humility', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('fact_interpretation', sa.String(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('final_interviews', 'technical_skills')
    op.drop_column('final_interviews', 'logical_thinking')
    op.drop_column('final_interviews', 'problem_solving')
    op.drop_column('final_interviews', 'career_vision')
    op.drop_column('final_interviews', 'leadership')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('final_interviews', sa.Column('leadership', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('career_vision', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('problem_solving', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('logical_thinking', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('final_interviews', sa.Column('technical_skills', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('final_interviews', 'notes')
    op.drop_column('final_interviews', 'fact_interpretation')
    op.drop_column('final_interviews', 'humility')
    op.drop_column('final_interviews', 'charm')
    op.drop_column('final_interviews', 'team_love')
    op.drop_column('final_interviews', 'initiative')
    op.drop_column('final_interviews', 'avoidance')
    op.drop_column('final_interviews', 'sincerity')
    op.drop_column('final_interviews', 'excuse')
    op.drop_column('final_interviews', 'assertion')
    op.drop_column('final_interviews', 'pass_fail')
    # ### end Alembic commands ###
